In [1]:
import sys
import os
from pathlib import Path

root = Path(os.getcwd()).parent
sys.path.append(str(Path(os.getcwd()).parent))
sys.path.append('C:/Users/Yejin Kim/Anaconda3/envs/aaa/Lib/site-packages')

In [2]:
from os import listdir
from os.path import isfile, join
import pandas as pd
import re
from datetime import datetime

### 파일 불러오기

In [3]:
path = os.path.join(root, 'data', 'raw')
files = [f for f in listdir(path) if isfile(join(path, f))]

seoul_routes = []
for file in files:
    filepath = os.path.join(path, file)
    route = pd.read_csv(filepath, encoding='CP949')
    seoul_routes.append(route)
seoul_routes = pd.concat(seoul_routes)
seoul_routes

C:\Users\Yejin Kim\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

,date,hospital,memo,patNo,reason,regNo,residence,route
0,5/12,-,NaN,확인중,이태원 클럽 관련,703,노원구,확인중
1,5/12,-,NaN,확인중,이태원 클럽 관련,702,동대문구,5월 9일: 11:34 ○○편의점 → 자택\n5월 10일: 23:35 ○○편의점 ...
2,5/12,서북병원,NaN,확인중,이태원 클럽 관련,701,성동구,5월 9일: 16:32 자택 외출(타지역 방문) → 23:57 버스(6211번) 꽃...
3,5/11,서북병원,NaN,확인중,이태원 클럽 관련,700,양천구,5월 8일: 14:30 강서구보건소 검체 채취(자가용) - 음성판정\n5월 9일: ...
4,5/11,서울의료원,NaN,10936,이태원 클럽 관련,699,서초구,5월 2일 ~ 3일: 이태원 클럽 방문\n5월 9일 ~ 11일: 자택\n5월 11일...
...,...,...,...,...,...,...,...,...
2616,1/31,서울의료원(퇴원),NaN,9,#5 접촉,5,성북구,이동경로 공개기간 경과
2617,1/30,서울의료원(퇴원),NaN,7,해외 접촉(중국 우한시),4,마포구,이동경로 공개기간 경과
2618,1/30,서울대학교병원(퇴원),NaN,6,#3 접촉,3,종로구,이동경로 공개기간 경과
2619,1/30,서울의료원(퇴원),NaN,5,해외 접촉(중국 우한시),2,중랑구,이동경로 공개기간 경과
2620,1/24,국립중앙의료원(퇴원),NaN,2,해외 접촉(중국 우한시),1,강서구,이동경로 공개기간 경과

### 중복된 경로 제거

In [4]:
seoul_routes = seoul_routes.drop_duplicates()
seoul_routes

,date,hospital,memo,patNo,reason,regNo,residence,route
0,5/12,-,NaN,확인중,이태원 클럽 관련,703,노원구,확인중
1,5/12,-,NaN,확인중,이태원 클럽 관련,702,동대문구,5월 9일: 11:34 ○○편의점 → 자택\n5월 10일: 23:35 ○○편의점 ...
2,5/12,서북병원,NaN,확인중,이태원 클럽 관련,701,성동구,5월 9일: 16:32 자택 외출(타지역 방문) → 23:57 버스(6211번) 꽃...
3,5/11,서북병원,NaN,확인중,이태원 클럽 관련,700,양천구,5월 8일: 14:30 강서구보건소 검체 채취(자가용) - 음성판정\n5월 9일: ...
4,5/11,서울의료원,NaN,10936,이태원 클럽 관련,699,서초구,5월 2일 ~ 3일: 이태원 클럽 방문\n5월 9일 ~ 11일: 자택\n5월 11일...
...,...,...,...,...,...,...,...,...
1159,7/17,서북병원(퇴원),NaN,13686,강남구 사무실 관련,1462,은평구,이동경로 공개기간 경과
1165,7/16,서울의료원(사망),NaN,13660,관악구 사무실 관련,1456,광진구,이동경로 공개기간 경과
1212,7/10,타시도 이관(퇴원),NaN,13363,확인 중,1409,광명시,이동경로 공개기간 경과
1216,7/10,서남병원(퇴원),NaN,13348,확인 중,1405,영등포구,이동경로 공개기간 경과
1601,6/09,서울대병원(퇴원),NaN,11886,양천구 운동시설 관련,1020,중구,이동경로 공개기간 경과

### 불필요한 columns 제거

In [5]:
seoul_routes = seoul_routes[['patNo', 'date', 'reason', 'route']]
seoul_routes

,patNo,date,reason,route
0,확인중,5/12,이태원 클럽 관련,확인중
1,확인중,5/12,이태원 클럽 관련,5월 9일: 11:34 ○○편의점 → 자택\n5월 10일: 23:35 ○○편의점 ...
2,확인중,5/12,이태원 클럽 관련,5월 9일: 16:32 자택 외출(타지역 방문) → 23:57 버스(6211번) 꽃...
3,확인중,5/11,이태원 클럽 관련,5월 8일: 14:30 강서구보건소 검체 채취(자가용) - 음성판정\n5월 9일: ...
4,10936,5/11,이태원 클럽 관련,5월 2일 ~ 3일: 이태원 클럽 방문\n5월 9일 ~ 11일: 자택\n5월 11일...
...,...,...,...,...
1159,13686,7/17,강남구 사무실 관련,이동경로 공개기간 경과
1165,13660,7/16,관악구 사무실 관련,이동경로 공개기간 경과
1212,13363,7/10,확인 중,이동경로 공개기간 경과
1216,13348,7/10,확인 중,이동경로 공개기간 경과
1601,11886,6/09,양천구 운동시설 관련,이동경로 공개기간 경과

### '확인중', '미부여',  '이동경로 공개기간 경과' 등 제거

In [6]:
seoul_routes['patNo'] = seoul_routes['patNo'].apply(str)
seoul_routes = seoul_routes[~seoul_routes.patNo.str.contains('확인중')]
seoul_routes = seoul_routes[~seoul_routes.patNo.str.contains('미부여')]
seoul_routes = seoul_routes[~seoul_routes.route.str.contains('이동경로 공개기간 경과')]
seoul_routes = seoul_routes[~seoul_routes.route.str.contains('확인중')]
seoul_routes

C:\Users\Yejin Kim\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,patNo,date,reason,route
4,10936,5/11,이태원 클럽 관련,5월 2일 ~ 3일: 이태원 클럽 방문\n5월 9일 ~ 11일: 자택\n5월 11일...
5,10932,5/11,이태원 클럽 관련,5월 8일: 07:30 ~ 08:00(양평) 자택에서 서울시 소재 회사 이동(자차)...
7,10935,5/11,이태원 클럽 관련,"5월 7일: 08:40~21:00 회사(타자치구, 지하철) → 21:00~ 자택\n..."
8,10927,5/11,이태원 클럽 관련,5월 6일: 12:40~13:00 명동역 하차 → 13:00~14:00 서울로 산책...
9,10929,5/11,이태원 클럽 관련,5월 8일: 09:30∼09:34 120번(광산사거리-수유역) → 09:37∼09:...
...,...,...,...,...
912,14698,8/11,관악구 요양병원,자가격리중 확진 판정으로 이동동선 없음<등록 : 동작구청>
933,14611,8/9,고양시 반석교회 관련(케네디상가),이동경로동장소·유형상호명(주소)노출일시소독여부비고홍은동교회**교회2020.08.02...
934,14623,8/9,고양시 반석교회 관련(케네디상가),이동경로동장소·유형상호명(주소)노출일시소독여부비고마포구행정기관중구보건소2020. 8...
941,14610,8/9,확인 중,이동경로동장소·유형상호명(주소)노출일시소독여부비고관내식당2020.8.2. 13:25...
958,14565,8/8,성북구 확진자 접촉,이동경로동장소·유형상호명(주소)노출일시소독여부비고홍은동직장**직장2020.07.30...

### Date column

In [7]:
hangeul = seoul_routes[seoul_routes['date'].str.match('\d*월 \d*일')== True]
hangeul

,patNo,date,reason,route
1,11110,05월 19일,이태원 클럽 관련,5월 16일 ~ 5월 18일: 자택 머무름\n5월 19일: 08:50 코로나19 검...
2,11092,05월 19일,확인 중(병원관련),5월 16일: ∼04:30 자택(번3동) → 04:30∼05:10 출근(자차) → ...
3,11091,05월 19일,이태원 클럽 관련,5월 9일: 11:55 쌍문1동 ○○상점(도보)\n5월 10일: ~ 5월 17일\...
4,11088,05월 19일,확인 중(병원관련),5월 16일: 17:22 마트(영희초교교차로)\n5월 17일: 자택\n5월 18일:...
5,11093,05월 19일,확인 중(병원관련),5월 16일 ~ 5월 17일: 17:00 타 지역 본가\n5월 17일: 18:36 ...
...,...,...,...,...
217,11800,06월 07일,확인 중,"6월 04일: 회사근무(지하철 : 까치산역 ↔ 발산역, 마스트 착용)\n6월 05일..."
218,11783,06월 07일,양천구 운동시설 관련,6월 02일: ~09:50 자택(수유3동) → 09:50~10:02 이동(택시) →...
219,11799,06월 07일,양천구 운동시설 관련,"6월 03일: 타구 동선 → 18:58 ○○편의점(도보, 접촉자 없음) → 타구 동..."
220,11798,06월 07일,확인 중,6월 05일: 자가격리 6. 5.(금) ~ 6. 18.(목) ※ 도봉구21번 확진자...
221,11784,06월 07일,확인 중,6월 04일: 15:05~15:11 옥수동주민센터 방문(자차 이용) → 16:00 ...

In [8]:
hangeul['date'] = '2020년 ' + hangeul['date'].astype(str)
hangeul['date'] = pd.to_datetime(hangeul['date'], format='%Y년 %m월 %d일')
hangeul

C:\Users\Yejin Kim\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Yejin Kim\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,patNo,date,reason,route
1,11110,2020-05-19,이태원 클럽 관련,5월 16일 ~ 5월 18일: 자택 머무름\n5월 19일: 08:50 코로나19 검...
2,11092,2020-05-19,확인 중(병원관련),5월 16일: ∼04:30 자택(번3동) → 04:30∼05:10 출근(자차) → ...
3,11091,2020-05-19,이태원 클럽 관련,5월 9일: 11:55 쌍문1동 ○○상점(도보)\n5월 10일: ~ 5월 17일\...
4,11088,2020-05-19,확인 중(병원관련),5월 16일: 17:22 마트(영희초교교차로)\n5월 17일: 자택\n5월 18일:...
5,11093,2020-05-19,확인 중(병원관련),5월 16일 ~ 5월 17일: 17:00 타 지역 본가\n5월 17일: 18:36 ...
...,...,...,...,...
217,11800,2020-06-07,확인 중,"6월 04일: 회사근무(지하철 : 까치산역 ↔ 발산역, 마스트 착용)\n6월 05일..."
218,11783,2020-06-07,양천구 운동시설 관련,6월 02일: ~09:50 자택(수유3동) → 09:50~10:02 이동(택시) →...
219,11799,2020-06-07,양천구 운동시설 관련,"6월 03일: 타구 동선 → 18:58 ○○편의점(도보, 접촉자 없음) → 타구 동..."
220,11798,2020-06-07,확인 중,6월 05일: 자가격리 6. 5.(금) ~ 6. 18.(목) ※ 도봉구21번 확진자...
221,11784,2020-06-07,확인 중,6월 04일: 15:05~15:11 옥수동주민센터 방문(자차 이용) → 16:00 ...

In [9]:
dash = seoul_routes[seoul_routes['date'].str.match('\d*/\d*')== True]
dash

,patNo,date,reason,route
4,10936,5/11,이태원 클럽 관련,5월 2일 ~ 3일: 이태원 클럽 방문\n5월 9일 ~ 11일: 자택\n5월 11일...
5,10932,5/11,이태원 클럽 관련,5월 8일: 07:30 ~ 08:00(양평) 자택에서 서울시 소재 회사 이동(자차)...
7,10935,5/11,이태원 클럽 관련,"5월 7일: 08:40~21:00 회사(타자치구, 지하철) → 21:00~ 자택\n..."
8,10927,5/11,이태원 클럽 관련,5월 6일: 12:40~13:00 명동역 하차 → 13:00~14:00 서울로 산책...
9,10929,5/11,이태원 클럽 관련,5월 8일: 09:30∼09:34 120번(광산사거리-수유역) → 09:37∼09:...
...,...,...,...,...
912,14698,8/11,관악구 요양병원,자가격리중 확진 판정으로 이동동선 없음<등록 : 동작구청>
933,14611,8/9,고양시 반석교회 관련(케네디상가),이동경로동장소·유형상호명(주소)노출일시소독여부비고홍은동교회**교회2020.08.02...
934,14623,8/9,고양시 반석교회 관련(케네디상가),이동경로동장소·유형상호명(주소)노출일시소독여부비고마포구행정기관중구보건소2020. 8...
941,14610,8/9,확인 중,이동경로동장소·유형상호명(주소)노출일시소독여부비고관내식당2020.8.2. 13:25...
958,14565,8/8,성북구 확진자 접촉,이동경로동장소·유형상호명(주소)노출일시소독여부비고홍은동직장**직장2020.07.30...

In [10]:
dash['date'] = '2020/' + dash['date'].astype(str)
dash['date'] = pd.to_datetime(dash['date'], format='%Y/%m/%d')
dash

C:\Users\Yejin Kim\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Yejin Kim\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,patNo,date,reason,route
4,10936,2020-05-11,이태원 클럽 관련,5월 2일 ~ 3일: 이태원 클럽 방문\n5월 9일 ~ 11일: 자택\n5월 11일...
5,10932,2020-05-11,이태원 클럽 관련,5월 8일: 07:30 ~ 08:00(양평) 자택에서 서울시 소재 회사 이동(자차)...
7,10935,2020-05-11,이태원 클럽 관련,"5월 7일: 08:40~21:00 회사(타자치구, 지하철) → 21:00~ 자택\n..."
8,10927,2020-05-11,이태원 클럽 관련,5월 6일: 12:40~13:00 명동역 하차 → 13:00~14:00 서울로 산책...
9,10929,2020-05-11,이태원 클럽 관련,5월 8일: 09:30∼09:34 120번(광산사거리-수유역) → 09:37∼09:...
...,...,...,...,...
912,14698,2020-08-11,관악구 요양병원,자가격리중 확진 판정으로 이동동선 없음<등록 : 동작구청>
933,14611,2020-08-09,고양시 반석교회 관련(케네디상가),이동경로동장소·유형상호명(주소)노출일시소독여부비고홍은동교회**교회2020.08.02...
934,14623,2020-08-09,고양시 반석교회 관련(케네디상가),이동경로동장소·유형상호명(주소)노출일시소독여부비고마포구행정기관중구보건소2020. 8...
941,14610,2020-08-09,확인 중,이동경로동장소·유형상호명(주소)노출일시소독여부비고관내식당2020.8.2. 13:25...
958,14565,2020-08-08,성북구 확진자 접촉,이동경로동장소·유형상호명(주소)노출일시소독여부비고홍은동직장**직장2020.07.30...

In [11]:
seoul_routes = pd.concat([hangeul, dash])
seoul_routes = seoul_routes.sort_values('date')
seoul_routes = seoul_routes.reset_index(drop=True)
seoul_routes

,patNo,date,reason,route
0,10771,2020-04-30,해외 접촉 추정(인도),4월 29일: 06:30 : 인도 뭄바이에서 인천공항 입국(마스크 착용)(해외입국자...
1,10779,2020-05-01,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
2,10789,2020-05-02,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C) → 15:..."
3,10790,2020-05-02,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판..."
4,10839,2020-05-08,이태원 클럽 관련,"5월 2일: 00:00 ~ 07:00 킹클럽(우사단로, 클럽), 퀸(우사단로, 주점..."
...,...,...,...,...
3428,16621,2020-08-20,확인 중,확인 중
3429,16438,2020-08-20,확인 중,확인 중
3430,16451,2020-08-20,성북구 사랑제일교회 관련,확인 중
3431,16421,2020-08-20,확인 중,확인 중
3432,16546,2020-08-20,확인 중,확인 중

### route column

In [12]:
date_aparted = pd.DataFrame()
for index, row in seoul_routes.iterrows():
    one_route = row['route']
    indices = []
    dates = []
    for match in re.finditer('\d*월 \d*일', one_route):
        indices.append(match.span()[0])
        date = datetime.strptime('2020년 %s' % one_route[match.start():match.end()], '%Y년 %m월 %d일')
        dates.append(date)
    parts = [one_route[i:j] for i, j in zip(indices, indices[1:]+[None])]
    for i, part in enumerate(parts):
        date_aparted = date_aparted.append({'patNo': row['patNo'], 'reason': row['reason'],
                     'date': dates[i], 'route': part}, ignore_index=True)

date_aparted

,date,patNo,reason,route
0,2020-04-29,10771,해외 접촉 추정(인도),4월 29일: 06:30 : 인도 뭄바이에서 인천공항 입국(마스크 착용)(해외입국자...
1,2020-04-30,10771,해외 접촉 추정(인도),4월 30일: 07:00 : 양성판정 → 13:00 서남병원으로 이송
2,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
3,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
4,2020-04-30,10779,해외 접촉 추정(미국),4월 30일: 자택에서 자가격리 유지\n
...,...,...,...,...
8469,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
8470,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
8471,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
8472,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
8473,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

In [13]:
visit_aprted = pd.DataFrame()
for index, row in date_aparted.iterrows():
    one_route = row['route']
    visits = one_route.split('→')
    for visit in visits:
        visit_aprted = visit_aprted.append({'date': row['date'], 'patNo': str(int(row['patNo'])),
                                       'reason': row['reason'], 'route': visit}, ignore_index=True)
        
visit_aprted

,date,patNo,reason,route
0,2020-04-29,10771,해외 접촉 추정(인도),4월 29일: 06:30 : 인도 뭄바이에서 인천공항 입국(마스크 착용)(해외입국자...
1,2020-04-29,10771,해외 접촉 추정(인도),09:27 : 서대문구 선별진료소 검체 채취 (마스크 착용)
2,2020-04-29,10771,해외 접촉 추정(인도),09:50 : 동일 택시로 귀가(마스크 착용)
3,2020-04-29,10771,해외 접촉 추정(인도),자가격리 유지\n
4,2020-04-30,10771,해외 접촉 추정(인도),4월 30일: 07:00 : 양성판정
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 자택 제거

In [112]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('자택')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('귀가')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('집에 머무름')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('집 도착')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('집 출발')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('집')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 보건소 제거

In [68]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('보건소')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('선별진료소')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('선별 검사')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('선별검사')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 택시 제거

In [20]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('택시')]
visit_aprted

,date,patNo,reason,route
1,2020-04-29,10771,해외 접촉 추정(인도),09:27 : 서대문구 선별진료소 검체 채취 (마스크 착용)
3,2020-04-29,10771,해외 접촉 추정(인도),자가격리 유지\n
4,2020-04-30,10771,해외 접촉 추정(인도),4월 30일: 07:00 : 양성판정
5,2020-04-30,10771,해외 접촉 추정(인도),13:00 서남병원으로 이송
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 양성 판정 제거

In [131]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('양성 판정')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('양성 확인')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('양성 확진')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('양성 판명')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('양성판정')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('확진 판정')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('확진판정')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('으로 이송')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('병원 이송')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('앰뷸런스')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('구급차')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('이송')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('서울의료원')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('양성')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('확진')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 도보 이동 제거

In [28]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('도보 이동')]
visit_aprted

,date,patNo,reason,route
1,2020-04-29,10771,해외 접촉 추정(인도),09:27 : 서대문구 선별진료소 검체 채취 (마스크 착용)
3,2020-04-29,10771,해외 접촉 추정(인도),자가격리 유지\n
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 타 지역 제거

In [30]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타 지역')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타구 이동')]
visit_aprted

,date,patNo,reason,route
1,2020-04-29,10771,해외 접촉 추정(인도),09:27 : 서대문구 선별진료소 검체 채취 (마스크 착용)
3,2020-04-29,10771,해외 접촉 추정(인도),자가격리 유지\n
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 상호명 비공개 제거

In [100]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('상호명 비공개')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('상호 비공개')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('비공개')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 자가격리 제거

In [48]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('자가 격리')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('자가격리')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 이동동선 없음 제거

In [108]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('이동동선 없음')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 직장 근무 제거

In [111]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('직장 근무')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('직장')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 타자치구 제거

In [132]:
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타자치구')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타 자치구')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타지역')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('우리 구 이동')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타구')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타시도')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('관외')]
visit_aprted = visit_aprted[~visit_aprted.route.str.contains('타지자체')]
visit_aprted

,date,patNo,reason,route
6,2020-04-17,10779,해외 접촉 추정(미국),4월 17일: 16:30 미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에...
8,2020-04-17,10779,해외 접촉 추정(미국),4월 17일 ~
15,2020-05-01,10789,해외 접촉 추정(터키),"5월 1일: 13:00 인천국제공항(대한항공 KE8956, 좌석 55C)"
16,2020-05-01,10789,해외 접촉 추정(터키),15:30 ~ 18:40 공항
22,2020-04-28,10790,해외 접촉 추정(미국),"4월 28일: 17:00 인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
...,...,...,...,...
21080,2020-08-15,16119,성북구 사랑제일교회 관련,8월 15일(토): \n
21081,2020-08-16,16119,성북구 사랑제일교회 관련,8월 16일(일): \n
21082,2020-08-17,16119,성북구 사랑제일교회 관련,8월 17일(월): \n
21083,2020-08-18,16119,성북구 사랑제일교회 관련,8월 18일(화): \n
21084,2020-08-19,16119,성북구 사랑제일교회 관련,8월 19일(수):

### 날짜만 있는 row 제거

In [133]:
regex_applied = pd.DataFrame()
for index, row in visit_aprted.iterrows():
    one_route = row['route']
    one_route = re.sub('\d*월 \d*일: \d*:\d* ~ \d*:\d*', '', one_route)
    one_route = re.sub('\d*월 \d*일: \d*:\d*', '', one_route)
    one_route = re.sub('\d*월 \d*일\s*\([가-힣]\):*', '', one_route)
    one_route = re.sub('\d*월 \d*일 ~', '', one_route)
    one_route = re.sub('\d*월 \d*일', '', one_route)
    one_route = re.sub('\d*월 \d*\([가-힣]\)', '', one_route)
    one_route = re.sub('\d*:\d* ~ \d*:\d*', '', one_route)
    one_route = re.sub('\d*:\d*', '', one_route)
    one_route = re.sub('^\s*,\s*', '', one_route)
    one_route = re.sub('^\s*', '', one_route)
    one_route = re.sub('^~\s*', '', one_route)
    one_route = re.sub('^∼\s*', '', one_route)
    one_route = re.sub('^-\s*', '', one_route)
    one_route = re.sub('$\s*', '', one_route)
    one_route = re.sub('$\n*', '', one_route)
    one_route = re.sub('^\d*일\([가-힣]\)', '', one_route)
    one_route = re.sub('^\s*', '', one_route)
    if one_route == "": continue
    
    regex_applied = regex_applied.append({'patNo': row['patNo'], 'reason': row['reason'],
                     'date': row['date'], 'route': one_route}, ignore_index=True)
        
regex_applied

           date  patNo         reason                                 route
0    2020-04-17  10779   해외 접촉 추정(미국)  미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에 입국
1    2020-05-01  10789   해외 접촉 추정(터키)          인천국제공항(대한항공 KE8956, 좌석 55C)
2    2020-05-01  10789   해외 접촉 추정(터키)                                   공항
3    2020-04-28  10790   해외 접촉 추정(미국)    인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정
4    2020-05-02  10839      이태원 클럽 관련       킹클럽(우사단로, 클럽), 퀸(우사단로, 주점) *도보
...         ...    ...            ...                                   ...
6216 2020-08-16  15789  성북구 사랑제일교회 관련        , ~소독완료마스크 착용, 접촉자 없음<등록 강북구청>
6217 2020-08-14  15833           확인 중          소독완료마스크 착용, 접촉자 없음<등록  강동구청>
6218 2020-08-14  15824  성북구 사랑제일교회 관련     소독완료식사 외 마스크 착용, 접촉자 9명<등록  강동구청>
6219 2020-08-15  15808  성북구 사랑제일교회 관련          소독완료마스크 착용, 접촉자 없음<등록  강동구청>
6220 2020-08-14  15972  성북구 사랑제일교회 관련         소독완료마스크 미착용, 접촉자 1명<등록  강북구청>

[6221 rows x 4 columns]

In [134]:
path = os.path.join(root, 'src', 'aaa.csv')
regex_applied.to_csv(path, encoding='utf-8-sig')