In [1]:
import sys
import os
from pathlib import Path

root = Path(os.getcwd()).parent
sys.path.append(str(Path(os.getcwd()).parent))

In [2]:
from api import GeoCoader
import pandas as pd
import re
from datetime import datetime

In [3]:
path = os.path.join(root, 'data', 'modified_route.csv')
route = pd.read_csv(path, encoding='utf-8-sig')
route

            date  patNo         reason                                 route
0     2020-04-17  10779          해외 접촉  미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에 입국
1     2020-05-01  10789          해외 접촉          인천국제공항(대한항공 KE8956, 좌석 55C)
2     2020-05-01  10789          해외 접촉                                   공항
3     2020-04-28  10790          해외 접촉    인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정
4     2020-05-02  10839      이태원 클럽 관련       킹클럽(우사단로, 클럽), 퀸(우사단로, 주점) *도보
...          ...    ...            ...                                   ...
5490  2020-08-17  15533  성북구 사랑제일교회 관련                소독완료접촉자 특정불가<등록  강북구청>
5491  2020-08-16  15789  성북구 사랑제일교회 관련        , ~소독완료마스크 착용, 접촉자 없음<등록 강북구청>
5492  2020-08-14  15824  성북구 사랑제일교회 관련     소독완료식사 외 마스크 착용, 접촉자 9명<등록  강동구청>
5493  2020-08-15  15808  성북구 사랑제일교회 관련          소독완료마스크 착용, 접촉자 없음<등록  강동구청>
5494  2020-08-14  15972  성북구 사랑제일교회 관련         소독완료마스크 미착용, 접촉자 1명<등록  강북구청>

[5495 rows x 4 columns]

### '소독'으로 시작하는 route 제외

In [4]:
indices = route[route['route'].str.contains('소독완료|소독 완료', na=False)].index
indices_to_del = []
for index in indices:
    mask = re.search("^소독", route.iloc[index]['route'])
    if mask is not None:
        indices_to_del.append(index)
        print(index, route.iloc[index]['route'])

route = route.drop(indices_to_del, inplace=False)
route = route.reset_index(drop=True)
route

5423 소독완료마스크 착용, 코로나 검사<등록  마포구청>
5446 소독완료※마스크 착용 ※코로나 검사<등록  마포구청>
5467 소독완료※마스크 착용 ※코로나 검사<등록  마포구청>
5468 소독완료※마스크 착용 ※코로나 검사<등록  마포구청>
5469 소독완료 ※마스크 착용 ※코로나 검사<등록  마포구청>
5474 소독 완료식사 외 마스크 착용, 접촉자 1명도봉로마트마트(강북구 도봉로)
5475 소독 완료마스크 착용, 접촉자 없음<등록  강북구청>
5476 소독완료접촉자 없음, 소독완료도봉로약국약국(강북구 도봉로)
5477 소독완료접촉자 없음, 소독완료도봉로외식업외식업(강북구 도봉로)
5478 소독완료접촉자 1명, 소독완료도봉로마트마트(강북구 도봉로)
5479 소독완료접촉자 없음, 소독완료도봉로정육점정육점(강북구 도봉로)
5480 소독완료접촉자 없음, 소독완료<등록  강북구청>
5489 소독완료 ※마스크 착용 ※코로나 검사<등록  마포구청>
5490 소독완료접촉자 특정불가<등록  강북구청>
5492 소독완료식사 외 마스크 착용, 접촉자 9명<등록  강동구청>
5493 소독완료마스크 착용, 접촉자 없음<등록  강동구청>
5494 소독완료마스크 미착용, 접촉자 1명<등록  강북구청>

,date,patNo,reason,route
0,2020-04-17,10779,해외 접촉,미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에 입국
1,2020-05-01,10789,해외 접촉,"인천국제공항(대한항공 KE8956, 좌석 55C)"
2,2020-05-01,10789,해외 접촉,공항
3,2020-04-28,10790,해외 접촉,"인천공항 입국(미국) *무증상, 동반 입국자 1명 음성 판정"
4,2020-05-02,10839,이태원 클럽 관련,"킹클럽(우사단로, 클럽), 퀸(우사단로, 주점) *도보"
...,...,...,...,...
5473,2020-08-13,15565,성북구 사랑제일교회 관련,"외식업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료\r\n8월 13, 1..."
5474,2020-08-14,15564,성북구 사랑제일교회 관련,"금융업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료"
5475,2020-08-12,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료"
5476,2020-08-16,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료"
5477,2020-08-16,15789,성북구 사랑제일교회 관련,", ~소독완료마스크 착용, 접촉자 없음<등록 강북구청>"

### * 이후 제외

In [5]:
indices_to_del = []
for index, row in route.iterrows():
    place = row['route']
    
    # '*' 이후
    regex_searched = re.search('\*', place)
    if regex_searched is None:
        continue
    
    # '*' 제거 후 공백인 경우
    new_place = place[:regex_searched.span()[0]]
    space_searched = re.search('^\s*$\s*', new_place)
    if space_searched is not None:
        indices_to_del.append(index)
    else:
        route.at[index, 'route'] = new_place

# 공백인 경우 삭제
route = route.drop(indices_to_del, inplace=False)
route = route.reset_index(drop=True)
route

,date,patNo,reason,route
0,2020-04-17,10779,해외 접촉,미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에 입국
1,2020-05-01,10789,해외 접촉,"인천국제공항(대한항공 KE8956, 좌석 55C)"
2,2020-05-01,10789,해외 접촉,공항
3,2020-04-28,10790,해외 접촉,인천공항 입국(미국)
4,2020-05-02,10839,이태원 클럽 관련,"킹클럽(우사단로, 클럽), 퀸(우사단로, 주점)"
...,...,...,...,...
5370,2020-08-13,15565,성북구 사랑제일교회 관련,"외식업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료\r\n8월 13, 1..."
5371,2020-08-14,15564,성북구 사랑제일교회 관련,"금융업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료"
5372,2020-08-12,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료"
5373,2020-08-16,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료"
5374,2020-08-16,15789,성북구 사랑제일교회 관련,", ~소독완료마스크 착용, 접촉자 없음<등록 강북구청>"

### use API

In [6]:
### name, type, latitude, longitude column 추가
route['type'] = ''
route['latitude'] = 0.0
route['longitude'] = 0.0
route

,date,patNo,reason,route,type,latitude,longitude
0,2020-04-17,10779,해외 접촉,미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에 입국,,0.0,0.0
1,2020-05-01,10789,해외 접촉,"인천국제공항(대한항공 KE8956, 좌석 55C)",,0.0,0.0
2,2020-05-01,10789,해외 접촉,공항,,0.0,0.0
3,2020-04-28,10790,해외 접촉,인천공항 입국(미국),,0.0,0.0
4,2020-05-02,10839,이태원 클럽 관련,"킹클럽(우사단로, 클럽), 퀸(우사단로, 주점)",,0.0,0.0
...,...,...,...,...,...,...,...
5370,2020-08-13,15565,성북구 사랑제일교회 관련,"외식업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료\r\n8월 13, 1...",,0.0,0.0
5371,2020-08-14,15564,성북구 사랑제일교회 관련,"금융업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료",,0.0,0.0
5372,2020-08-12,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료",,0.0,0.0
5373,2020-08-16,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료",,0.0,0.0
5374,2020-08-16,15789,성북구 사랑제일교회 관련,", ~소독완료마스크 착용, 접촉자 없음<등록 강북구청>",,0.0,0.0

In [7]:
geo_api = GeoCoader()

print('size: %d' % len(route.index))
indices_to_del = []
for index, row in route.iterrows():
    if index % 100 == 0:
        print(index)
    
    information = geo_api.get_information(row['route'])
    if information.empty:
        indices_to_del.append(index)
        continue
    route.at[index, 'latitude'] = information['lat'].values[0]
    route.at[index, 'longitude'] = information['lng'].values[0]
    route.at[index, 'type'] = information['type'].values[0]
    
route = route.drop(indices_to_del, inplace=False)
route = route.reset_index(drop=True)
route

size: 5375
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300

,date,patNo,reason,route,type,latitude,longitude
0,2020-04-17,10779,해외 접촉,미국 LA 출발 아시아나항공(OZ201) 이용해 인천공항에 입국,airport,33.941589,-118.408530
1,2020-05-01,10789,해외 접촉,"인천국제공항(대한항공 KE8956, 좌석 55C)",airport,37.460191,126.440696
2,2020-05-01,10789,해외 접촉,공항,airport,37.442055,127.108157
3,2020-04-28,10790,해외 접촉,인천공항 입국(미국),airport,37.460191,126.440696
4,2020-05-02,10839,이태원 클럽 관련,"킹클럽(우사단로, 클럽), 퀸(우사단로, 주점)",bar,37.533634,126.995761
...,...,...,...,...,...,...,...
5323,2020-08-13,15565,성북구 사랑제일교회 관련,"외식업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료\r\n8월 13, 1...",political,37.631575,127.027822
5324,2020-08-14,15564,성북구 사랑제일교회 관련,"금융업(강북구 도봉로), 마스크 착용, 접촉자 없음, 소독완료",political,37.631575,127.027822
5325,2020-08-12,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료",establishment,37.633069,127.036275
5326,2020-08-16,15564,성북구 사랑제일교회 관련,"외식업(강북구 한천로), 마스크 착용, 접촉자 없음, 소독완료",establishment,37.633069,127.036275
5327,2020-08-16,15789,성북구 사랑제일교회 관련,", ~소독완료마스크 착용, 접촉자 없음<등록 강북구청>",establishment,37.639777,127.025518

In [ ]:
path = os.path.join(root, 'data', 'modified_route2.csv')
route.to_csv(path, encoding='utf-8-sig', index=False)